services:
  postgres:
    image: postgres:15-alpine
    ports:
      - 5433:5432 # enables connecting locally via psql
    environment:
      POSTGRES_DB: webapp_dev
      POSTGRES_HOST_AUTH_METHOD: trust
